### ISSUE TITLE
Error    default_arg = yaml.load(f) 

### ISSUE THREAD

**Issue by Cronusf** [yysijie/st-gcn#172]
(st-gcn) gydx@gydx-HP-Z6-G4-Workstation:~/A-YFT/st-gcn$ python main.py demo --openpose '~/home/A-YFT/openpose/build' --video '~/home/A-YFT/st-gcn/test/test.avi'
/home/gydx/A-YFT/st-gcn/processor/io.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  default_arg = yaml.load(f)
Traceback (most recent call last):
  File "/home/gydx/anaconda3/envs/st-gcn/lib/python3.6/site-packages/torchlight-1.0-py3.6.egg/torchlight/io.py", line 82, in load_weights
    __doc__ = _io._TextIOBase.__doc__
  File "/home/gydx/anaconda3/envs/st-gcn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "data_bn.num_batches_tracked", "st_gcn_networks.0.tcn.0.num_batches_tracked", "st_gcn_networks.0.tcn.3.num_batches_tracked", "st_gcn_networks.1.tcn.0.num_batches_tracked", "st_gcn_networks.1.tcn.3.num_batches_tracked", "st_gcn_networks.2.tcn.0.num_batches_tracked", "st_gcn_networks.2.tcn.3.num_batches_tracked", "st_gcn_networks.3.tcn.0.num_batches_tracked", "st_gcn_networks.3.tcn.3.num_batches_tracked", "st_gcn_networks.4.tcn.0.num_batches_tracked", "st_gcn_networks.4.tcn.3.num_batches_tracked", "st_gcn_networks.4.residual.1.num_batches_tracked", "st_gcn_networks.5.tcn.0.num_batches_tracked", "st_gcn_networks.5.tcn.3.num_batches_tracked", "st_gcn_networks.6.tcn.0.num_batches_tracked", "st_gcn_networks.6.tcn.3.num_batches_tracked", "st_gcn_networks.7.tcn.0.num_batches_tracked", "st_gcn_networks.7.tcn.3.num_batches_tracked", "st_gcn_networks.7.residual.1.num_batches_tracked", "st_gcn_networks.8.tcn.0.num_batches_tracked", "st_gcn_networks.8.tcn.3.num_batches_tracked", "st_gcn_networks.9.tcn.0.num_batches_tracked", "st_gcn_networks.9.tcn.3.num_batches_tracked". 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 29, in <module>
    p = Processor(sys.argv[2:])
  File "/home/gydx/A-YFT/st-gcn/processor/io.py", line 28, in __init__
    self.load_weights()
  File "/home/gydx/A-YFT/st-gcn/processor/io.py", line 75, in load_weights
    self.arg.ignore_weights)
  File "/home/gydx/anaconda3/envs/st-gcn/lib/python3.6/site-packages/torchlight-1.0-py3.6.egg/torchlight/io.py", line 89, in load_weights
    
  File "/home/gydx/anaconda3/envs/st-gcn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "data_bn.num_batches_tracked", "st_gcn_networks.0.tcn.0.num_batches_tracked", "st_gcn_networks.0.tcn.3.num_batches_tracked", "st_gcn_networks.1.tcn.0.num_batches_tracked", "st_gcn_networks.1.tcn.3.num_batches_tracked", "st_gcn_networks.2.tcn.0.num_batches_tracked", "st_gcn_networks.2.tcn.3.num_batches_tracked", "st_gcn_networks.3.tcn.0.num_batches_tracked", "st_gcn_networks.3.tcn.3.num_batches_tracked", "st_gcn_networks.4.tcn.0.num_batches_tracked", "st_gcn_networks.4.tcn.3.num_batches_tracked", "st_gcn_networks.4.residual.1.num_batches_tracked", "st_gcn_networks.5.tcn.0.num_batches_tracked", "st_gcn_networks.5.tcn.3.num_batches_tracked", "st_gcn_networks.6.tcn.0.num_batches_tracked", "st_gcn_networks.6.tcn.3.num_batches_tracked", "st_gcn_networks.7.tcn.0.num_batches_tracked", "st_gcn_networks.7.tcn.3.num_batches_tracked", "st_gcn_networks.7.residual.1.num_batches_tracked", "st_gcn_networks.8.tcn.0.num_batches_tracked", "st_gcn_networks.8.tcn.3.num_batches_tracked", "st_gcn_networks.9.tcn.0.num_batches_tracked", "st_gcn_networks.9.tcn.3.num_batches_tracked". 
This error occurred while running demo. How to solve it?

**Comment by XJX777** [comment]
Hello,thanks for your share,I meet the same question as you do, it also shows 
RuntimeError: Error(s) in loading state_dict for Model:
Unexpected key(s) in state_dict: "data_bn.num_batches_tracked", "st_gcn_networks.0.tcn.0.num_batches_tracked", "st_gcn_networks.0.tcn.3.num_batches_tracked", "st_gcn_networks.1.tcn.0.num_batches_tracked", "st_gcn_networks.1.tcn.3.num_batches_tracked", "st_gcn_networks.2.tcn.0.num_batches_tracked", "st_gcn_networks.2.tcn.3.num_batches_tracked", "st_gcn_networks.3.tcn.0.num_batches_tracked", "st_gcn_networks.3.tcn.3.num_batches_tracked", "st_gcn_networks.4.tcn.0.num_batches_tracked", "st_gcn_networks.4.tcn.3.num_batches_tracked", "st_gcn_networks.4.residual.1.num_batches_tracked", "st_gcn_networks.5.tcn.0.num_batches_tracked", "st_gcn_networks.5.tcn.3.num_batches_tracked", "st_gcn_networks.6.tcn.0.num_batches_tracked", "st_gcn_networks.6.tcn.3.num_batches_tracked", "st_gcn_networks.7.tcn.0.num_batches_tracked", "st_gcn_networks.7.tcn.3.num_batches_tracked", "st_gcn_networks.7.residual.1.num_batches_tracked", "st_gcn_networks.8.tcn.0.num_batches_tracked", "st_gcn_networks.8.tcn.3.num_batches_tracked", "st_gcn_networks.9.tcn.0.num_batches_tracked", "st_gcn_networks.9.tcn.3.num_batches_tracked".

This error occurred while running these commands:
python main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml
python main.py recognition -c config/st_gcn/ntu-xview/test.yaml
python main.py recognition -c config/st_gcn/ntu-xsub/test.yaml

PyTorch version:0.4.0           Cuda: 8.0        GPU: 2*1080Ti          Dataset used:  kinetics-skeleton dataset
Have you fix the problem? I have been got  stuck on this problem for almost a week,I sincerely need your help .
Thank you so very much. @yysijie @yjxiong @Cronusf @lshiwjx

**Comment by yysijie** [comment]
@XJX777, @Cronusf,
Can I know the version of pytorch you used? 
And did you downloaded the models from GoogleDrive?

**Comment by XJX777** [comment]
Thanks for your reply. 
My pytorch version is 0.4.0 (installed from the official website) ,python  3.6.8 ,cuda 8.0 .
And I also tried to download the pretrained models from GoogleDrive. 
After that I tried to train as the default settings using the dataset (Kinetics-skeleton and NTU RGB+D)，and got a  good  result ,good top1, small loss. This way works.
Thanks for your great work!

**Comment by XJX777** [comment]
> @XJX777, @Cronusf,
> Can I know the version of pytorch you used?
> And did you downloaded the models from GoogleDrive?

Thanks for your reply.
My pytorch version is 0.4.0 (installed from the official website) ,python 3.6.8 ,cuda 8.0 .
And I also tried to download the pretrained models from GoogleDrive.
After that I tried to train as the default settings using the dataset (Kinetics-skeleton and NTU RGB+D)，and got a good result ,good top1, small loss. This way works.
Thanks for your great work!

**Comment by yysijie** [comment]
@XJX777, the pretrained models in BaiduYun is broken. We have fixed them. Thank you for your feedback.

**Comment by Cronusf** [comment]
> > @XJX777, @Cronusf,
> > Can I know the version of pytorch you used?
> > And did you downloaded the models from GoogleDrive?
> 
> Thanks for your reply.
> My pytorch version is 0.4.0 (installed from the official website) ,python 3.6.8 ,cuda 8.0 .
> And I also tried to download the pretrained models from GoogleDrive.
> After that I tried to train as the default settings using the dataset (Kinetics-skeleton and NTU RGB+D)，and got a good result ,good top1, small loss. This way works.
> Thanks for your great work!


Hello, how do you solve your problem? I downloaded the model file again with the same error.

**Comment by XJX777** [comment]
> > > @XJX777, @Cronusf,
> > > Can I know the version of pytorch you used?
> > > And did you downloaded the models from GoogleDrive?
> > 
> > 
> > Thanks for your reply.
> > My pytorch version is 0.4.0 (installed from the official website) ,python 3.6.8 ,cuda 8.0 .
> > And I also tried to download the pretrained models from GoogleDrive.
> > After that I tried to train as the default settings using the dataset (Kinetics-skeleton and NTU RGB+D)，and got a good result ,good top1, small loss. This way works.
> > Thanks for your great work!
> 
> Hello, how do you solve your problem? I downloaded the model file again with the same @yysijie @XJX777
Hello,I did not solve the problem of pretrained model,but I trained with the default setting and get a good result.
You can download it from here,to have a try.
https://pan.baidu.com/s/1JrfpRqt0uF8AydiJuxANZw
password:j4rt

**Comment by lauhsu** [comment]
@ @XJX777 the Baidu cloud link is invalid，can you repair it?
